name: UpdateMembers

on:
  schedule:
    - cron: '*/5 * * * *' #Every x minutes for testing
#    - cron: "0 * * * *"  #Nightly

jobs:
  update-members:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Set Up Python 3.7
        uses: actions/setup-python@v1
        with:
          python-version: 3.7

      - name: Enable Pip Cache
        uses: actions/cache@v1
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install Dependencies
        run: |
          python --version
          pip install -r requirements.txt

      - name: Decrypt Gdrive Service Account Secret
        env:
          LARGE_SECRET_PASSPHRASE: ${{ secrets.LARGE_SECRET_PASSPHRASE }}
        run: |
          cd .github/scripts
          decrypt_secret.sh


      - name: Update aws-uswest2 team
        env:
          PANGEOBOT_TOKEN = ${{ secrets.PANGEOBOT_TOKEN }}
        run: |
          cd .github/scripts
          ./update_membership.py aws-uswest2


      - name: Update us-central1-b-gcp team
        env:
          PANGEOBOT_TOKEN = ${{ secrets.PANGEOBOT_TOKEN }}
        run: |
          cd .github/scripts
          ./update_membership.py us-central1-b-gcp
